[package]
name = "base16-egui-themes"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.33"
serde = { version = "1", features = ["derive"] }
schemars = "1.1"
strum = "0.27"
strum_macros = "0.27"
